package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, REPOERT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,
	SITE_HOME_PAGE, SITE_HOME_PAGE2 ,SITE_LOGIN_PAGE, SITE_REGISTRATION_PAGE,
	SITE_CHANGEPASSWORD_PAGE,
	SITE_EDITPROFILE_PAGE, SITE_FORGOTPASSWORD_PAGE, SITE_DETAILS_PAGE, SITE_FAVORITE_PAGE,
	SITE_FAVORITE_PAGE2, SITE_SHARE_PAGE, SITE_HOME3, SITE_HOME4, SITE_HOME5
	

}
